site_name: Documentación de Rodrigo Zárate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.keys
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
# Use the ReadTheDocs theme
theme:
  name: material
  highlightjs: true 
  palette:
      - scheme: default
        primary: black

  features:
    - content.code.copy
    - content.tooltips
extra_css:
  - https://use.fontawesome.com/releases/v6.5.2/css/all.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css

nav:
  - Home: index.md
  - Materias 5to semestre: 
      - Sistemas embebidos: 
        - Comparacion de sistemas embebidos: Comparacion_de_sistemas_embebidos.md
        - Practicas Raspberry Pi Pico 2:
          - Outputs basicos: Practica1_Outputs_basicos.md
          - Inputs: Inputs.md
          - Pong: Pong.md
          - Temporizadores: timer.md
          - Simon dice: SimonDice.md
          - PWM:
            - Motor DC: pwm_motor.md
            - Buzzer: control_pwm.md
            - Onda Senoidal: seno_pwm.md
          - UART Led: ComUARTled.md
          - UART Led 2: Uart_LEDS.md
          - Examen 2: Examen2.md
          - ADC:
            - ADC Luxometro: ADC_lux.md
            - ADC Servomotor: ADC_servo.md
          - I2C: Comunicacion_I2C.md
      - Proyectos 4:
        - Proyecto RANA: Proyecto_Rana.md
        - cafetera: Cafetera.md
        - El Mercado: ElMercado.md
        - Creando Valor: CreandoValor.md